WCS\GestyBundle\Entity\Justificatif:
    type: entity

    fields:
        path:
            type: string
            length: 255

    manyToOne:
        signataire:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: justificatifs
