Application\Sonata\Userbundle\Entity\User:
    properties:
        nom:
            - NotBlank: ~
            - Regex:
                pattern: '/"#{}<>=+|~&()`_^@°%$£ø*µ§!?,:;.²/'
                match: false

        prenom:
            - NotBlank: ~
            - Regex:
                pattern: '/"#{}<>=+|~&()`_^@°%$£ø*µ§!?,:;.²/'
                match: false

        adresse:
            - NotBlank: ~
            - Regex:
                pattern: '/"#{}<>=+|~&()`_^@°%$£ø*µ§!?,:;.²/'
                match: false

        codePostal:
            - Length:
                min: 5
                max: 5
            - Regex:
                pattern: '/\d/'
                match: true

        commune:
            - NotBlank: ~
            - Regex:
                pattern: '/"#{}<>=+|~&()`_^@°%$£ø*µ§!?,:;.²/'
                match: false

        telephone:
            - Length:
                min: 10
                max: 10
            - Regex:
                pattern: '/\d/'
                match: true
                message: Your name cannot contain a string

        telephoneSecondaire:
            - Length:
                min: 10
                max: 10
            - Regex:
                pattern: '/\d/'
                match:   true
                message: Your name cannot contain a string

        numeroIban:
            - Length:
                min: 27
                max: 27
            - Regex:
                pattern: '/"#{}<>=+|~&()`_^@°%$£ø*µ§!?,:;.²/'
                match: false

        caf:
            - Length:
                min: 7
                max: 7
            - Regex:
                pattern: '/\d/'
                match:   true
                message: Your name cannot contain a string
