wcs_cantine_feries:
    resource: "@WCSCantineBundle/Resources/config/routing/feries.yml"
    prefix:   /feries

gesty_cantine_eleve:
    resource: "@WCSCantineBundle/Resources/config/routing/eleve.yml"
    prefix:   /

gesty_cantine_cantine:
    resource: "@WCSCantineBundle/Resources/config/routing/cantine.yml"
    prefix:   /cantine

gesty_cantine_tapgarderie:
    resource: "@WCSCantineBundle/Resources/config/routing/tapgarderie.yml"
    prefix:   /tapgarderie

gesty_cantine_voyage:
    resource: "@WCSCantineBundle/Resources/config/routing/voyage.yml"
    prefix:   /voyage

gesty_cantine_dame:
    resource: "@WCSCantineBundle/Resources/config/routing/dameCantine.yml"
    prefix:   /canteenManager

wcs_cantine_dashboard:
    path: /dashboard
    defaults: { _controller: "WCSCantineBundle:Eleve:dashboard"  }

gesty_parent_download:
    path: /download/{type_file}
    defaults: { _controller: "WCSCantineBundle:Download:downloadParent"  }

gesty_comptable_download:
    path: /download/{type_file}/{id_user}
    defaults: { _controller: "WCSCantineBundle:Download:downloadComptable"  }
