services:
#    gesty.example:
#        class: CantineBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    sonata.block.service.stat:
        class: WCS\CantineBundle\Block\Service\StatElevesBlockService
        arguments: [ "sonata.block.service.stat", '@templating', '@sonata.admin.pool', '@doctrine.orm.entity_manager', '@security.context']
        tags:
            - { name: sonata.block }
