services:
    sonata.block.service.stat:
        class: WCS\CantineBundle\Block\Service\StatElevesBlockService
        arguments:
            - "sonata.block.service.stat"
            - '@service_container'
        tags:
            - { name: sonata.block }

    wcs.daysoff:
        class: WCS\CantineBundle\Service\AdditionalDayOffList
        arguments: ['@doctrine.orm.entity_manager']

    wcs.eleve.paramconverter:
        class: WCS\CantineBundle\Request\ParamConverter\EleveParamConverter
        tags:
            - { name: request.param_converter, priority: 1, converter: wcs.eleve.paramconverter }
        arguments: ['@service_container']
