WCS\CantineBundle\Entity\Eleve:
    properties:
        nom:
           - Length:
                min: 2
                max: 20


        prenom:
            - Length:
                min: 2
                max: 20


        allergie:
            - Length:
                min: 1
                max: 40

