gesty\CantineBundle\Entity\Formulaire:
    properties:
        nom:
            - NotBlank: ~
            - Regex:
                pattern: '/"#{}<>=+|~&()`_^@°%$£ø*µ§!?,:;.²/'
                match: true

        prenom:
            - NotBlank: ~
            - Regex:
                pattern: '/"#{}<>=+|~&()`_^@°%$£ø*µ§!?,:;.²/'
                match: true

        adresse:
            - NotBlank: ~
            - Regex:
                pattern: '/"#{}<>=+|~&()`_^@°%$£ø*µ§!?,:;.²/'
                match: true

        codePostal:
            - Length:
                min: 5
                max: 5
                exactMessage: "Code invalide"
            - Regex:
                pattern: '/\d/'
                match: true

        commune:
            - NotBlank: ~
            - Regex:
                pattern: '/"#{}<>=+|~&()`_^@°%$£ø*µ§!?,:;.²/'
                match: true

        telephone:
            - Length:
                min: 10
                max: 10
            - Regex:
                pattern: '/\d/'
                match: true
                message: Your name cannot contain a string

        telephoneSecondaire:
            - Length:
                min: 10
                max: 10
            - Regex:
                pattern: '/\d/'
                match:   true
                message: Your name cannot contain a string

        numeroIban:
            - Length:
                min: 27
                max: 27
            - Regex:
                pattern: '/"#{}<>=+|~&()`_^@°%$£ø*µ§!?,:;.²/'
                match: true

        caf:
            - Length:
                min: 7
                min: 7
            - Regex:
                pattern: '/\d/'
                match:   true
                message: Your name cannot contain a string
