WCS\CantineBundle\Entity\Calendar:
    type: entity
    table: null
    repositoryClass: WCS\CantineBundle\Entity\CalendarRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        period:
            type: string
            length: 255
        start:
            type: date
        end:
            type: date
        vacancesToussaintStart:
            type: date
            column: vacances_toussaint_start
        vacancesToussaintEnd:
            type: date
            column: vacances_toussaint_end
        vacancesNoelStart:
            type: date
            column: vacances_noel_start
        vacancesNoelEnd:
            type: date
            column: vacances_noel_end
        vacancesHiverStart:
            type: date
            column: vacances_hiver_start
        vacancesHiverEnd:
            type: date
            column: vacances_hiver_end
        vacancesPrintempsStart:
            type: date
            column: vacances_printemps_start
        vacancesPrintempsEnd:
            type: date
            column: vacances_printemps_end
        vacancesEte:
            type: date
            column: vacances_ete
        feriePaques:
            type: date
            column: ferie_paques
        feriePentecote:
            type: date
            column: ferie_pentecote
    lifecycleCallbacks: {  }
