WCS\CantineBundle\Entity\Division:
    type: entity
    repositoryClass: WCS\CantineBundle\Entity\DivisionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        grade:
            type: string
            length: 255

        headTeacher:
            type: string
            length: 255

    lifecycleCallbacks: {  }

    manyToOne:
        school:
            targetEntity: WCS\CantineBundle\Entity\School
            inversedBy: divisions

    oneToMany:
        eleves:
            targetEntity: WCS\CantineBundle\Entity\Eleve
            mappedBy: division
            cascade: {persist, remove}
    manyToMany:
        voyages:
            targetEntity: Voyage
            mappedBy: divisions


