WCS\CantineBundle\Entity\Eleve:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        dateDeNaissance:
            type: date
            column: date_de_naissance
        RegimeSansPorc:
            type: boolean
            column: Regime_Sans_Porc
        allergie:
            type: string
            column: allergie
            nullable: true
        idFoyer:
            type: integer
            column: id_foyer
            nullable: true
        idEtablissement:
            type: integer
            column: id_etablissement
        atteste :
            type: boolean
            column: atteste
        autorise:
            type: boolean
            column: autorise
        certifie:
            type: boolean
            column: certifie

    lifecycleCallbacks: {  }
