WCS\CantineBundle\Entity\Eleve:
    type: entity
    repositoryClass: WCS\CantineBundle\Entity\EleveRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        dateDeNaissance:
            type: date
            column: date_de_naissance
        regimeSansPorc:
            type: boolean
        allergie:
            type: string
            column: allergie
            nullable: true
        habits:
            type: array

    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: eleves
        division:
            targetEntity: Division
            inversedBy: eleves

    oneToMany:
        lunches:
            targetEntity: WCS\CantineBundle\Entity\Lunch
            mappedBy: eleve
            joinColumn:
                name: date
                referencedColumnName: date


    lifecycleCallbacks: {  }
