WCS\CantineBundle\Entity\Eleve:
    type: entity
    repositoryClass: WCS\CantineBundle\Entity\EleveRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        dateDeNaissance:
            type: date
            column: date_de_naissance
        regimeSansPorc:
            type: boolean
        allergie:
            type: string
            column: allergie
            nullable: true
        idFoyer:
            type: integer
            column: id_foyer
            nullable: true
        Etablissement:
            type: string
            length: 255
            column: etablissement
        atteste :
            type: boolean
            column: atteste
        autorise:
            type: boolean
            column: autorise
        certifie:
            type: boolean
            column: certifie
        dates:
            type: text
            nullable: true
        habits:
            type: array


    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: eleves



    lifecycleCallbacks: {  }
