WCS\CantineBundle\Entity\School:
    type: entity
    repositoryClass: WCS\CantineBundle\Entity\SchoolRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        adress:
            type: string
            length: 255
        phone:
            type: string
            length: 255
            nullable: true
        active_cantine:
            type: boolean
            options:
                default: true
        active_tap:
            type: boolean
            options:
                default: true
        active_garderie:
            type: boolean
            options:
                default: true
        active_voyage:
            type: boolean
            options:
                default: true
    lifecycleCallbacks: {  }

    oneToMany:
        divisions:
            targetEntity: WCS\CantineBundle\Entity\Division
            mappedBy: school
            cascade: {persist, remove}
            orphanRemoval: true
