WCS\CantineBundle\Entity\School:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        adress:
            type: string
            length: 255
        phone:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }

    oneToMany:
        divisions:
            targetEntity: WCS\CantineBundle\Entity\Division
            mappedBy: school
            cascade: {persist, remove}
            orphanRemoval: true
