WCS\CantineBundle\Entity\Tap:
    type: entity
    table: null
    repositoryClass: WCS\CantineBundle\Entity\TapRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
            nullable: true
        status:
            type: integer
            length: 1
            nullable: true

    lifecycleCallbacks: {  }

    manyToOne:
        eleve:
            targetEntity: WCS\CantineBundle\Entity\Eleve
            inversedBy: taps
