Gesty\GestyBundle\Entity\Etablissement:
    type: entity
    table: null
    repositoryClass: Gesty\GestyBundle\Entity\EtablissementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        classe:
            type: string
            length: 255
        instituteur:
            type: string
            length: 255
    lifecycleCallbacks: {  }
