imports:
    - { resource: config_dev.yml }

parameters:

    wcs.datenow.date: '2016-06-21'

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db

security:
    firewalls:
        main:
            http_basic: ~
        admin:
            http_basic: ~

liip_functional_test: ~
