wcs_gesty:
    resource: "@WCSGestyBundle/Resources/config/routing.yml"
    prefix:   /

wcs_cantine:
    resource: "@WCSCantineBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin


_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin


sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile
    methods: [GET, POST]


sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

eleve_list_les_ecureuils:
    path:     /list_les_ecureuils
    defaults: { _controller: "WCSCantineBundle:ListInscrits:listLesEcureuils" }

eleve_list_roland_garros:
    path:     /list_roland_garros
    defaults: { _controller: "WCSCantineBundle:ListInscrits:listRolandGarros" }

eleve_list_notre_dame:
    path:     /list_notre_dame_des_fleurs
    defaults: { _controller: "WCSCantineBundle:ListInscrits:listNotreDame" }