# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
      sonata.admin.eleve:
           class: WCS\CantineBundle\Admin\EleveAdmin
           tags:
               - { name: sonata.admin, manager_type: orm, group: "wcs.group.eleve", label: "Eleve" }
           arguments:
               - ~
               - WCS\CantineBundle\Entity\Eleve
               - ~
               - '@wcs.datenow'

      sonata.admin.division:
           class: WCS\CantineBundle\Admin\DivisionAdmin
           tags:
               - { name: sonata.admin, manager_type: orm, group: "wcs.group.school", label: "Liste des classes" }
           arguments:
               - ~
               - WCS\CantineBundle\Entity\Division
               - ~

      sonata.admin.school:
           class: WCS\CantineBundle\Admin\SchoolAdmin
           tags:
               - { name: sonata.admin, manager_type: orm, group: "wcs.group.school", label: "Liste des écoles" }
           arguments:
               - ~
               - WCS\CantineBundle\Entity\School
               - ~

      sonata.admin.feries:
           class: WCS\CantineBundle\Admin\FeriesAdmin
           tags:
               - { name: sonata.admin, manager_type: orm, group: "wcs.group.feries", label: "Jours fériés" }
           arguments:
               - ~
               - WCS\CantineBundle\Entity\Feries
               - ~
               - '@wcs.datenow'

      sonata.admin.lunch:
           class: WCS\CantineBundle\Admin\LunchAdmin
           tags:
               - { name: sonata.admin, manager_type: orm, group: "wcs.group.lunches", label: "Inscription" }
           arguments:
                - ~
                - WCS\CantineBundle\Entity\Lunch
                - ~

      sonata.admin.tap:
            class: WCS\CantineBundle\Admin\TapAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "wcs.group.tapgarderie", label: "Inscriptions TAP" }
            arguments:
                 - ~
                 - WCS\CantineBundle\Entity\Tap
                 - ~

      sonata.admin.garderie:
            class: WCS\CantineBundle\Admin\GarderieAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "wcs.group.tapgarderie", label: "Inscriptions Garderie" }
            arguments:
                - ~
                - WCS\CantineBundle\Entity\Garderie
                - ~

      sonata.user.profile.form.type:
            class: Application\Sonata\UserBundle\Form\Type\ProfileType
            arguments: [ "Application\\Sonata\\UserBundle\\Entity\\User" ]
            tags:
                - { name: "form.type", alias: "application_sonata_user_profile"}

      application.sonata_user_listener:
            class: Application\Sonata\UserBundle\EventListener\EditProfileListener
            tags:
                - { name: doctrine.event_listener, event: preUpdate }
            arguments: ['@mailer']

      application.sonata_mail_listener:
            class: Application\Sonata\UserBundle\EventListener\EmailListener
            arguments: ['@mailer']


      sonata.admin.voyage:
             class: WCS\CantineBundle\Admin\VoyageAdmin
             tags:
                 - { name: sonata.admin, manager_type: orm, group: "wcs.group.voyage", label: "Liste des voyages/sorties" }
             arguments:
                 - ~
                 - WCS\CantineBundle\Entity\Voyage
                 - ~

#      sonata.admin.inscription:
#              class: WCS\CantineBundle\Admin\InscriptionAdmin
#              tags:
#                  - { name: sonata.admin, manager_type: orm, group: "wcs.group.voyage", label: "Incription élève" }
#              arguments:
#                  - ~
#                  - WCS\CantineBundle\Entity\Eleve
#                  - ~

