# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
      sonata.admin.eleve:
           class: WCS\CantineBundle\Admin\EleveAdmin
           tags:
               - { name: sonata.admin, manager_type: orm, group: "wcs.group.eleve", label: "Eleve" }
           arguments:
               - ~
               - WCS\CantineBundle\Entity\Eleve
               - ~

      sonata.admin.division:
           class: WCS\CantineBundle\Admin\DivisionAdmin
           tags:
               - { name: sonata.admin, manager_type: orm, group: "wcs.group.school", label: "Liste des classes" }
           arguments:
               - ~
               - WCS\CantineBundle\Entity\Division
               - ~

      sonata.admin.school:
           class: WCS\CantineBundle\Admin\SchoolAdmin
           tags:
               - { name: sonata.admin, manager_type: orm, group: "wcs.group.school", label: "Liste des écoles" }
           arguments:
               - ~
               - WCS\CantineBundle\Entity\School
               - ~

      sonata.admin.feries:
           class: WCS\CantineBundle\Admin\FeriesAdmin
           tags:
               - { name: sonata.admin, manager_type: orm, group: "wcs.group.feries", label: "Jours fériés" }
           arguments:
               - ~
               - WCS\CantineBundle\Entity\Feries
               - ~

      sonata.admin.lunch:
                 class: WCS\CantineBundle\Admin\LunchAdmin
                 tags:
                     - { name: sonata.admin, manager_type: orm, group: "wcs.group.lunches", label: "Liste des repas" }
                 arguments:
                     - ~
                     - WCS\CantineBundle\Entity\Lunch
                     - ~

      sonata.user.profile.form.type:
            class: Application\Sonata\UserBundle\Form\Type\ProfileType
            arguments: [ "Application\\Sonata\\UserBundle\\Entity\\User" ]
            tags:
                - { name: "form.type", alias: "application_sonata_user_profile"}

      wcs.eleve.profile.form.type:
            class: WCS\CantineBundle\Form\Type\EleveType
            arguments: [ "WCS\\CantineBundle\\Entity\\Eleve"]
            tags:
                - {name: "form.type", alias: "wcs_cantinebundle_eleve"}

      application.sonata_user_listener:
            class: Application\Sonata\UserBundle\EventListener\EditProfileListener
            tags:
                - { name: doctrine.event_listener, event: preUpdate }
            arguments: ['@mailer']

      application.sonata_mail_listener:
            class: Application\Sonata\UserBundle\EventListener\EmailListener
            arguments: ['@mailer']


      sonata.admin.voyage:
             class: WCS\CantineBundle\Admin\VoyageAdmin
             tags:
                 - { name: sonata.admin, manager_type: orm, group: "wcs.group.voyage", label: "Liste des voyages" }
             arguments:
                 - ~
                 - WCS\CantineBundle\Entity\Voyage
                 - ~
