# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
      sonata.admin.eleve:
           class: Gesty\GestyBundle\Admin\EleveAdmin
           tags:
               - { name: sonata.admin, manager_type: orm, group: "Eleve", label: "Eleve" }
           arguments:
               - ~
               - Gesty\GestyBundle\Entity\Eleve
               - ~
      sonata.user.profile.form.type:
            class: Application\Sonata\UserBundle\Form\Type\ProfileType
            arguments: [ "Application\Sonata\UserBundle\Entity\User" ]
            tags:
                - { name: "form.type", alias: "application_sonata_user_profile"}
