parameters:
    # url vers le calendrier scolaire
    # en commentaire, l'url vers le calendrier du ministère de l'éducation nationale.
    # Pour éviter un téléchargement à chaque accès à un script utilisant ce calendrier
    # il est préférable de le stocker dans un répertoire de l'application

#    wcs.calendar_scolaire.file: 'http://www.education.gouv.fr/download.php?file=http://cache.media.education.gouv.fr/ics/Calendrier_Scolaire_Zone_B.ics'
    wcs.calendrier_scolaire.file: '%kernel.root_dir%/Resources/files/Calendrier_Scolaire_Zone_B.ics'
    wcs.datenow.date: ''
    wcs.daysoff.class: WCS\CalendrierBundle\Service\DaysOffDefault


services:

    wcs.daysoff:
        class: '%wcs.daysoff.class%'
        arguments: ['@doctrine.orm.entity_manager']

    wcs.datenow:
        class: WCS\CalendrierBundle\Service\DateNow
        arguments: ['%wcs.datenow.date%']

    wcs.calendrierscolaire:
        class: WCS\CalendrierBundle\Service\Service
        arguments:
            - '%wcs.calendrier_scolaire.file%'
            - '@wcs.datenow'
            - '@wcs.daysoff'

