parameters:
    # url vers le calendrier scolaire
    # en commentaire, l'url vers le calendrier du ministère de l'éducation nationale.
    # remarque : la première fois que ce service est appelé dans un script,
    # ce fichier est téléchargé. Mais il n'est pas stocké.
    # Pour éviter de multiples téléchargements à chaque accès à un script utilisant ce calendrier
    # il est préférable de le stocker dans un répertoire de l'application

#    wcs.calendar_scolaire.file: 'http://www.education.gouv.fr/download.php?file=http://cache.media.education.gouv.fr/ics/Calendrier_Scolaire_Zone_B.ics'
    wcs.calendrier_scolaire.file: '%kernel.root_dir%/Resources/files/Calendrier_Scolaire_Zone_B.ics'


services:
    wcs.calendrierscolaire:
        class: WCS\CalendrierBundle\Service\Service
        arguments: ['%wcs.calendrier_scolaire.file%']
