wcs_gesty_homepage:
    path:     /
    defaults: { _controller: 'WCSGestyBundle:Dashboard:index' }
    methods: [GET, POST]



eleve_tipi:
    path:    /tipi
    defaults: { _controller: "WCSGestyBundle:Tipi:form" }
    methods:   [GET, POST]

