# Gesty/GestyBundle/Resources/config/admin.yml
services:
  sonata.admin.eleve:
      class: Gesty\GestyBundle\Admin\EleveAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Eleve", label: "Eleve" }
      arguments: [null, Gesty\GestyBundle\Entity\Eleve, GestyGestyBundle:ElevesAdmin]

  sonata.admin.foyer:
      class: Gesty\GestyBundle\Admin\FoyerAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Foyer", label: "Foyer" }
      arguments: [null, Gesty\GestyBundle\Entity\Foyer, GestyGestyBundle:FoyerAdmin]