# Gesty/GestyBundle/Resources/config/admin.yml
services:
  sonata.admin.eleve:
      class: Gesty\GestyBundle\Admin\EleveAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Eleve", label: "Eleve" }
      arguments:
          - ~
          - Gesty\GestyBundle\Entity\Eleve
          - ~

  sonata.admin.foyer:
      class: Gesty\GestyBundle\Admin\FoyerAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Foyer", label: "Foyer" }
      arguments:
          - ~
          - Gesty\GestyBundle\Entity\Foyer
          - ~