gesty_gesty_homepage:
    path:     /hello/{name}
    defaults: { _controller: GestyGestyBundle:Default:index }

gesty_gesty_register:
    path:      /register
    defaults:   {_controller: GestyGestyBundle:Default:register}



