gesty_gesty_homepage:
    path:     /
    defaults: { _controller: GestyGestyBundle:Default:index }

gesty_gesty_register:
    path:      /login
    defaults:   {_controller: GestyGestyBundle:Default:register}



