wcs_employee_home:
    path: /
    defaults: {_controller: 'WCSEmployeeBundle:Home:index' }

wcs_employee_schools:
    path: /{activity}/schools
    defaults: {_controller: 'WCSEmployeeBundle:Home:showSchools' }
    methods: [GET]

# ----------------------------------------------------------------------------------------
wcs_employee_daylist:
    path: /{activity}/{id}/daylist
    defaults: { _controller: 'WCSEmployeeBundle:Daylist:show' }
    requirements:
        id: \d+
    methods: [POST, GET]

wcs_employee_remove:
    path: /{activity}/{id}/daylist/remove/{id_activity}
    defaults: { _controller: "WCSEmployeeBundle:Daylist:remove" }
    methods: [GET, DELETE]

wcs_employee_canteen_orders:
    path: /cantine/reservation
    defaults: { _controller: "WCSEmployeeBundle:Canteen:showOrders" }
