Application\Sonata\UserBundle\Entity\User:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        adresse:
            type: string
            length: 255
            nullable: true
        codePostal:
            type: integer
            column: code_postal
            nullable: true
        commune:
            type: string
            length: 255
            nullable: true
        telephoneSecondaire:
            type: integer
            column: telephone_secondaire
            nullable: true
        caf:
            type: string
            length: 255
            nullable: true
        modeDePaiement:
            type: integer
            column: mode_de_paiement
            nullable: true
        numeroIban:
            type: string
            length: 255
            column: numero_iban
            nullable: true
        mandatActif:
            type: boolean
            column: mandat_actif
            nullable: true
        justificatif:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
