Application\Sonata\UserBundle\Entity\User:
    type: entity
    table: fos_user_user
    repositoryClass: Application\Sonata\UserBundle\Entity\UserRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        adresse:
            type: string
            length: 255
            nullable: true
        codePostal:
            type: integer
            column: code_postal
            nullable: true
        commune:
            type: string
            length: 255
            nullable: true
        telephoneSecondaire:
            type: integer
            column: telephone_secondaire
            nullable: true
        caf:
            type: string
            length: 255
            nullable: true
        modeDePaiement:
            type: string
            length: 255
            column: mode_de_paiement
            nullable: true
        numeroIban:
            type: string
            length: 255
            column: numero_iban
            nullable: true
        mandatActif:
            type: boolean
            column: mandat_actif
            nullable: true
        validation:
            type: boolean
            column: validation
            nullable: true
        path_domicile:
            type: string
            length: 255
            nullable: true
        path_prestations:
            type: string
            length: 255
            nullable: true
        path_salaire_1:
            type: string
            length: 255
            nullable: true
        path_salaire_2:
            type: string
            length: 255
            nullable: true
        path_salaire_3:
            type: string
            length: 255
            nullable: true
        path_impots:
            type: string
            length: 255
            nullable: true


    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]


    oneToMany:
        eleves:
            targetEntity: WCS\CantineBundle\Entity\Eleve
            mappedBy: user
            cascade: {persist, remove}
            orphanRemoval: true



