wcs_gesty_ecoles:
    path: /
    defaults: {_controller: WCSCantineBundle:CanteenManager:index }

wcs_cantine_todayList:
    path:     /todayList/{schoolId}
    defaults: { _controller: "WCSCantineBundle:CanteenManager:todayList" }
    requirements:
        schoolId: \d+

delete_pupil:
    path:     /todayList/{schoolId}/{id}
    defaults: { _controller: "WCSCantineBundle:CanteenManager:delete" }
    methods: [GET, DELETE]

reserve_meal:
    path: /reservation
    defaults: { _controller: "WCSCantineBundle:CanteenManager:commande" }
