eleve_create:
    path:     /create
    defaults: { _controller: "WCSCantineBundle:Eleve:create" }
    methods:  [GET, POST]

eleve_edit:
    path:     /{id}/edit
    defaults: { _controller: "WCSCantineBundle:Eleve:edit" }
    methods:  [GET]

eleve_update:
    path:     /{id}/update
    defaults: { _controller: "WCSCantineBundle:Eleve:update" }
    methods:  [POST, PUT]
