eleve:
    path:     /
    defaults: { _controller: "WCSCantineBundle:Eleve:index" }

eleve_create:
    path:     /create
    defaults: { _controller: "WCSCantineBundle:Eleve:create" }


eleve_edit:
    path:     /{id}/edit
    defaults: { _controller: "WCSCantineBundle:Eleve:edit" }

eleve_update:
    path:     /{id}/update
    defaults: { _controller: "WCSCantineBundle:Eleve:update" }
    methods:  [POST, PUT]

eleve_delete:
    path:     /{id}/delete
    defaults: { _controller: "WCSCantineBundle:Eleve:delete" }
    methods:  [POST, DELETE]

eleve_show:
    path:     /{id}/show
    defaults: { _controller: "WCSCantineBundle:Eleve:show" }

eleve_create_inscr_voy:
    path:     /createvoy
    defaults: { _controller: "WCSCantineBundle:Eleve:createInscriptionVoyage" }

eleve_create_inscr_tapgarderie:
    path:     /createtapgarderie
    defaults: { _controller: "WCSCantineBundle:Eleve:createInscriptionTapGarderie" }
