Application\Sonata\UserBundle\Entity\User:      # le lien pour la doc, http://symfony.com/doc/current/reference/constraints.html
    properties:
        lastname:
           - Length:
                min: 2
                max: 20
           - Regex:
                pattern: '/["#{}@€<>=+|~&()`_^@°\[%$£\]ø*µ§!?,:;.²0-9]/'
                match: false

        firstname:
            - Length:
                min: 2
                max: 20
            - Regex:
                pattern: '/["#{}@€<>=+|~&()`_^@°\[%$£\]ø*µ§!?,:;.²0-9]/'
                match: false

        adresse:
            - Length:
                min: 1
                max: 40
            - Regex:
                pattern: '/["#{}@€<>=+|~&()`_^@°\[%$£\]ø*µ§!?,:;.²]/'
                match: false

        codePostal:
            - Length:
                min: 5
                max: 5
            - Regex:
                pattern: '/[A-Z"#{}@€<>=+|~&()`_^@°\[%$£\]ø*µ§!?,:;.²a-z]/'
                match: false

        phone:
            - Length:
                min: 10
                max: 10
            - Regex:
                pattern: '/[A-Z"#{}€@<>=+|~&()`_^@°\[%$£\]ø*µ§!?,:;.²a-z]/'
                match: false

        telephoneSecondaire:
            - Length:
                min: 10
                max: 10
            - Regex:
                pattern: '/[A-Z"#{}€@<>=+|~&()`_^@°\[%$£\]ø*µ§!?,:;.²a-z]/'
                match: false

        numeroIban:
            - Length:
                min: 27
                max: 27
            - Regex:
                pattern: '/["#{}€@<>=+|~&()`_^@°\[%$£\]ø*µ§!?,:;.²]/'
                match: false

        caf:
            - Length:
                min: 7
                max: 7
            - Regex:
                pattern: '/["#{}€@<>=+|~&()`_^@°\[%$£\]ø*µ§!?,:;.²a-z]/'
                match: false

        file_domicile:
            - File:
                maxSize: 1024k
                mimeTypes: [application/pdf, image/jpeg, image/png]
                mimeTypesMessage: Veuillez télécharger un fichier PDF, JPEG ou PNG valide.

        file_prestations:
            - File:
                maxSize: 1024k
                mimeTypes: [application/pdf, image/jpeg, image/png]
                mimeTypesMessage: Veuillez télécharger un fichier PDF, JPEG ou PNG valide.

        file_salaire_1:
            - File:
                maxSize: 1024k
                mimeTypes: [application/pdf, image/jpeg, image/png]
                mimeTypesMessage: Veuillez télécharger un fichier PDF, JPEG ou PNG valide.

        file_salaire_1:
            - File:
                maxSize: 1024k
                mimeTypes: [application/pdf, image/jpeg, image/png]
                mimeTypesMessage: Veuillez télécharger un fichier PDF, JPEG ou PNG valide.

        file_impots:
            - File:
                maxSize: 1024k
                mimeTypes: [application/pdf, image/jpeg, image/png]
                mimeTypesMessage: Veuillez télécharger un fichier PDF, JPEG ou PNG valide.




